#!/usr/bin/env python3
from __future__ import annotations
import argparse
import os
import subprocess
from pathlib import Path

def create_pr(repo_root: Path, branch_name: str, commit_message: str, file_changes: list, base_branch: str = 'main'):
    """Create a GitHub PR using gh CLI (requires authentication)."""
    os.chdir(repo_root)
    subprocess.run(['git', 'checkout', '-b', branch_name], check=True)
    for file_path in file_changes:
        subprocess.run(['git', 'add', file_path], check=True)
    subprocess.run(['git', 'commit', '-m', commit_message], check=True)
    subprocess.run(['git', 'push', '--set-upstream', 'origin', branch_name], check=True)
    pr_url = subprocess.run(['gh', 'pr', 'create', '--base', base_branch, '--head', branch_name,
                             '--title', commit_message, '--body', 'Auto-generated by HGS'],
                            capture_output=True, text=True).stdout.strip()
    print(f"PR created: {pr_url}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo-root', default='.')
    ap.add_argument('--branch', required=True)
    ap.add_argument('--message', required=True)
    ap.add_argument('--files', required=True, help='comma-separated list of files')
    ap.add_argument('--base', default='main')
    args = ap.parse_args()
    repo_root = Path(args.repo_root).resolve()
    file_list = [f.strip() for f in args.files.split(',')]
    create_pr(repo_root, args.branch, args.message, file_list, args.base)

if __name__ == '__main__':
    main()